// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    $('#prev-button').click(function() {
      return $('#myCarousel').Carousel3d('prev');
    });
    return $('#next-button').click(function() {
      return $('#myCarousel').Carousel3d('next');
    });
  });

}).call(this);
