// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    return $('#searchBtn').click(function() {
      $(this).attr('href', '/search?' + $.param({
        searchText: $('#searchText').val()
      }));
      return true;
    });
  });

}).call(this);
