// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    $('.card').hide();
    return $.ajax({
      type: "GET",
      url: $("#idCard").val() + "/json",
      encoding: "UTF-8",
      contentType: "application/json; charset=UTF-8",
      dataType: 'json',
      success: function(json, headers, status) {
        var $contact, col, i, j, ref, results;
        col = json.contactCards.length;
        $('.card').show('slow');
        $('.card').css({
          position: 'relative'
        });
        results = [];
        for (i = j = 0, ref = col; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
          $contact = $('<div>').attr({
            'class': 'contactCards'
          });
          $contact.text(json.contactCards[i].text);
          $('.card').append($contact);
          results.push($contact.css({
            position: 'absolute',
            top: json.contactCards[i].yposition,
            left: json.contactCards[i].xposition
          }, font - {
            size: json.contactCards[i].font
          }, {
            color: json.contactCards[i].color
          }, background - {
            color: json.contactCards[i].bgcolor
          }, {
            width: json.contactCards[i].width,
            height: json.contactCards[i].height
          }));
        }
        return results;
      },
      error: function(data, headers, status) {
        return alert("error!!!");
      }
    });
  });

}).call(this);
